CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  username VARCHAR(15) UNIQUE,
  password TEXT,
  fullname VARCHAR(15),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);